#Enum file

class RedditAPI:
    
    FIELDS = ["REDDIT_CLIENT_ID", "REDDIT_CLIENT_SECRET",
                     "REDDIT_USER_AGENT", "REDDIT_USERNAME",
                     "REDDIT_PASSWORD"]

    CLIENT_ID = "REDDIT_CLIENT_ID"
    CLIENT_SECRET = "REDDIT_CLIENT_SECRET"
    USER_AGENT = "REDDIT_USER_AGENT"
    USERNAME = "REDDIT_USERNAME"
    PASSWORD = "REDDIT_PASSWORD"
